backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers


from django.contrib.sitemaps.views import sitemap
from bulletin_board.sitemaps import JobSitemap, CompanySitemap, ApplicantSitemap, BlogSitemap, CustomSitemap

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bulletin_board.urls')),

    path('industrial/', include('industrial.urls')),

    path('payment/', include('payment.urls')),

    path('api/v1/', include(router.urls)),
    path('api-auth/',
         include('rest_framework.urls', namespace='rest_framework')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('sitemap.xml', sitemap, {
        'sitemaps': {
            "jobs": JobSitemap,
            "companies": CompanySitemap,
            "applicants": ApplicantSitemap,
            "blog": BlogSitemap,
            "custom": CustomSitemap
        }
    },
         name='django.contrib.sitemaps.views.sitemap')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page

from . import views

app_name = 'bulletin_board'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('for-company/', views.ForCompany.as_view(), name='for_company'),

    path('blog/', views.BlogList.as_view(), name='blog_list'),
    path('blog/<int:blog_id>', views.BlogView.as_view(), name='blog_view'),

    path('companies/', views.CompaniesList.as_view(), name='companies_list'),
    path('companies/<int:company_id>', views.CompanyView.as_view(), name='company_view'),

    path('orders/', views.JobsCatalog.as_view(), name='jobs_catalog'),
    path('orders/<int:job_id>/', views.JobView.as_view(), name='job_view'),
    path('orders/<int:job_id>/apply', csrf_exempt(views.ApplyJob.as_view()), name='apply_job'),

    path('summary/', views.SummaryCatalog.as_view(), name='sum_catalog'),
    path('summary/<int:sum_id>/', views.SummaryView.as_view(), name='sum_view'),

    path('application_to_admin', views.ApplicationToAdmin.as_view(), name='application_to_admin'),

    path('doc-1', views.Doc1.as_view(), name='doc_1'),
    path('doc-2', views.Doc2.as_view(), name='doc_2'),

    path('delete_education/',
         csrf_exempt(views.DeleteSummaryEducation.as_view()),
         name='delete_education'),

    path('delete_experience/',
         csrf_exempt(views.DeleteSummaryExperience.as_view()),
         name='delete_experience'),

    path('robots.txt', views.get_robots_txt, name='robots_txt'),
    # path('sitemap.xml', views.get_sitemap_xml, name='sitemap_xml')
]

backend/drf/urls.py
# from django.contrib import admin
# from django.urls import path
# from . import views
# from django.views.decorators.csrf import csrf_exempt
#
# app_name = "drf"
#
# urlpatterns = [
#     path('dashboardapp_api/', csrf_exempt(views.DashboardAppAPI.as_view()),
#          name='dashboardapp_api'),
# ]

backend/industrial/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "industrial"

urlpatterns = [

    path('admin/request/publish_job_<int:job_id>',
         views.AdminPublishJob.as_view(), name='admin_publish_job'),
    path('admin/request/reject_job_<int:job_id>',
         views.AdminRejectJob.as_view(), name='admin_reject_job'),
    path('admin/request/close_job_<int:job_id>', views.AdminCloseJob.as_view(),
         name='admin_close_job'),

    path('reg-<str:user_ref_code>/', views.RefLinkView.as_view(),
         name='ref_link_view'),

    path('signin/', views.SignInView.as_view(), name='sign_in'),
    path('signinapp/', views.SignInAppView.as_view(), name='sign_in_app'),
    path('signupapp/', views.SignUpAppView.as_view(), name='sign_up_app'),
    path('get_company/', csrf_exempt(views.GetCompanyByInn.as_view()),
         name='get_company_by_inn'),

    path('signup/', views.SignUpView.as_view(), name='sign_up'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('confirm_email/', views.ConfirmEmailView.as_view(),
         name='confirm_email'),  # Поддтвержденые почты

    path('confirm_email_app/', views.ConfirmEmailAppView.as_view(),
         name='confirm_emailapp'),

    path('confirm_email/send_again',
         views.ResendConfirmEmailCodeView.as_view(),
         name='re_confirm_email_code'),  # Поддтвержденые почты

    path('confirm_email/send_againapp',
         views.ResendConfirmEmailCodeAppView.as_view(),
         name='re_confirm_email_codeapp'),  # Поддтвержденые почты

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

    path('dashboardapp/', views.DashboardAPP.as_view(), name='dashboardapp'),

    path('summary/', csrf_exempt(views.Summary.as_view()),
         name='summary'),

    path('edit_summary/', csrf_exempt(views.EditSummary.as_view()),
         name='edit_summary'),

    path('edit_summary/education/',
         csrf_exempt(views.EditSummaryEducation.as_view()),
         name='education'),

    path('edit_summary/experience/',
         csrf_exempt(views.EditSummaryExperience.as_view()),
         name='experience'),

    path('delete_tags/',
         csrf_exempt(views.TagsAPI.as_view()),
         name='delete_tags'),

    # path('delete_summary/education/',
    #      csrf_exempt(views.DeleteSummaryEducation.as_view()),
    #      name='delete_education'),
    #
    # path('delete_summary/experience/',
    #      csrf_exempt(views.DeleteSummaryExperience.as_view()),
    #      name='delete_experience'),

    path('profile/', views.Profile.as_view(), name='profile'),

    path('profile/edit_brand_info/', views.ProfileEditBrandInfo.as_view(),
         name='edit_brand_info'),

    path('profile/edit_administrator_info/',
         views.ProfileEditAdministratorInfo.as_view(),
         name='edit_administrator_info'),

    path('profile/edit_company_description/',
         views.ProfileEditCompanyDescription.as_view(),
         name='edit_company_description'),

    path('profile/edit_user_password/',
         views.ProfileEditUserPassword.as_view(), name='edit_user_password'),

    path('jobs/new', csrf_exempt(views.AddNewJob.as_view()), name='add_new_job'),
    path('jobs/list', csrf_exempt(views.JobsList.as_view()), name='jobs_list'),

    path('jobs/list_api', csrf_exempt(views.JobListAPI.as_view()),
         name='jobs_list_api'),
    path('jobs/pay_for_job_api', csrf_exempt(views.PayForJobAPI.as_view()),
         name='pay_for_job_api'),

    path('jobs/<int:job_id>/edit', csrf_exempt(views.EditJob.as_view()), name='edit_job'),
    path('jobs/<int:job_id>/view', views.ViewJob.as_view(), name='view_job'),
    path('jobs/<int:job_id>/delete', views.DeleteJob.as_view(),
         name='delete_job'),

    path('candidates/<int:resp_id>/delete', views.DeleteResponse.as_view(),
         name='delete_resp'),

    path('candidates/', views.CandidatesList.as_view(), name='candidates'),

    path('payment/', views.Payment.as_view(), name='payment'),

    path('user_agreement/', views.UserAgreement.as_view(),
         name='user_agreement'),
    path('instruction/', views.Instruction.as_view(), name='instruction'),
    path('support/', views.Support.as_view(), name='support'),

    path('user_agreementapp/', views.UserAgreementApp.as_view(),
         name='user_agreementapp'),
    path('instructionapp/', views.InstructionApp.as_view(), name='instructionapp'),
    path('supportapp/', views.SupportApp.as_view(), name='supportapp'),


    path('finance/', views.Finance.as_view(), name='finance'),

    path('payment_invoices/', views.PaymentInvoices.as_view(),
         name='payment_invoices'),

    path('payment_invoices/', views.PaymentInvoice.as_view(),
         name='payment_invoice'),
    path('payment_invoices/<int:invoice_id>/', views.PaymentInvoice.as_view(),
         name='payment_invoice'),
    path('payment_invoices/<int:invoice_id>/check',
         views.PaymentInvoiceCheck.as_view(), name='payment_invoice_check'),

    path('forgot_password/', views.ForgotPasswordView.as_view(),
         name='forgot_password'),
    path('enter_key/', views.EnterKeyView.as_view(),
         name='enter_key'),
    path('signre/', views.SignReView.as_view(), name='signre'),

]

backend/payment/urls.py
from django.urls import path
from payment import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'payment'

urlpatterns = [
    path('new_tinkoff_card_payment', csrf_exempt(views.NewTinkoffCardPayment.as_view()),
         name='new_tinkoff_card_payment'),
]

backend/payment/models.py
from django.db import models


class ModelBase(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class PaymentInvoice(ModelBase):
    """Счеть на оплату """

    class Statuses(models.TextChoices):
        waiting = 'waiting', "Ожидается"
        succeed = 'succeed', "Успешно"
        canceled = 'canceled', "Отменен"

    status = models.CharField(max_length=20, choices=Statuses.choices)
    amount = models.FloatField()
    comment = models.CharField(max_length=500)

    company = models.ForeignKey("industrial.Company",
                                on_delete=models.RESTRICT,
                                related_name='payment_invoices')

    @property
    def invoice_number(self):
        return 3600000 + self.id

    def __str__(self):
        return f"{self.company}, {self.status}, {self.amount}"


class TinkoffCardPayment(ModelBase):
    """Тинькофф платеж картой"""

    payment_invoice = models.OneToOneField(
        PaymentInvoice,
        on_delete=models.RESTRICT,
        related_name="tinkoff_card_payment"
    )
    terminal_key = models.CharField(max_length=20)
    status = models.CharField(max_length=20, blank=True, null=True)
    tinkoff_payment_id = models.CharField(max_length=20, blank=True, null=True)
    tinkoff_payment_url = models.CharField(max_length=150, blank=True,
                                           null=True)
    order_id = models.CharField(max_length=40)
    amount = models.FloatField()
    description = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.tinkoff_payment_id}, {self.status}, {self.amount}"

backend/industrial/forms.py
from django import forms


class SignUpForm(forms.Form):
    inn = forms.CharField(label="ИНН", max_length=12, min_length=8)
    email = forms.EmailField(label="Email")
    password = forms.CharField(label="Пароль", min_length=8, max_length=32)
    password_repeat = forms.CharField(label="Пароль повторно", min_length=8, max_length=32)


class SignUpappForm(forms.Form):
    tel = forms.CharField(label="Телефон", max_length=20, min_length=11)
    email = forms.EmailField(label="Email")
    password = forms.CharField(label="Пароль", min_length=8, max_length=32)
    password_repeat = forms.CharField(label="Пароль повторно", min_length=8, max_length=32)


class SignInForm(forms.Form):
    email = forms.EmailField(label="Email")
    password = forms.CharField(label="Пароль", min_length=8, max_length=32)


class ForgotPasswordFormKey(forms.Form):
    key = forms.CharField(max_length=12)


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label="Email")


class SignReForm(forms.Form):
    password1 = forms.CharField(label="Пароль1", min_length=6, max_length=32)
    password2 = forms.CharField(label="Пароль2", min_length=6, max_length=32)
    # password2 = forms.PasswordInput()


class EditAdministratorInfo(forms.Form):
    name = forms.CharField(max_length=250)
    position = forms.CharField(max_length=250)
    phone = forms.CharField(max_length=250)
    email = forms.EmailField(max_length=250)


class EditCompanyDescription(forms.Form):
    description = forms.CharField(max_length=4096)


class EditUserPasswordForm(forms.Form):
    password = forms.CharField(label="Пароль", min_length=8, max_length=32)
    new_password = forms.CharField(label="Пароль", min_length=8, max_length=32)
    new_password_repeat = forms.CharField(label="Пароль повторно", min_length=8, max_length=32)

backend/payment/views.py
import logging
import json
from django.views import View
from django.http import JsonResponse
from django.shortcuts import reverse
from django.http.request import HttpRequest

from core_base.logger import get_logger
from industrial.mixins import OnlyIndustrialWorkerMixin
from payment.models import PaymentInvoice
from payment import selectors as py_selectors
from payment import services as py_services

logger = get_logger('pay_views_log', level=logging.INFO)


class NewTinkoffCardPayment(OnlyIndustrialWorkerMixin, View):
    def post(self, request: HttpRequest):
        company_instance = request.user.industrial_worker.company
        js = json.loads(request.body)
        amount = int(js['amount'])
        if company_instance and amount:
            tf_card_payment_instance = py_services.create_payment_by_tinkoff_card(
                company=company_instance,
                amount=amount
            )
            return JsonResponse(
                {
                    'invoice_url': reverse(
                        'industrial:payment_invoice',
                        kwargs={
                            'invoice_id': tf_card_payment_instance.payment_invoice.id}
                    ),
                    'payment_url': tf_card_payment_instance.tinkoff_payment_url
                }
            )

backend/industrial/templates/industrial/pages/confirm_email.html
{% extends 'industrial/base.html' %}
{% load static %}

{% block page_title %}Пожалуйста подтвердите свою почту!{% endblock %}

{% block page_content %}

    {% if not user.is_email_confirmed %}

        <h1>Пожалуйста подтвердите свою почту!</h1>

        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3">

                    <label for="pxp-company-name" class="form-label">
                        Код для подтверждения отправлено на почту: <b>{{ user.email }}</b>
                    </label>

                    <form method="post" action="{% url 'industrial:confirm_email' %}">
                        {% csrf_token %}
                        <input
                                type="text"
                                id="pxp-company-name"
                                class="form-control"
                                placeholder="Код подтверждения"
                                name="confirmation_code"
                                required="required"
                        >

                        {% if is_code_wrong %}
                            <br>
                            <h4 class="text-danger">Код подтверждения введен неверно</h4>
                        {% endif %}

                        {% if code_is_sent %}
                            <br>
                            <h4 class="text-success">Код подтверждения отправлен на вашу электронную почту</h4>
                        {% endif %}

                        <br>
                        <button
                                type="submit"
                                class="btn btn-success float-end"
                        >
                            Подтвердить
                        </button>
                    </form>
                </div>

                <div>
                    <br>
                    <br>
                    <form action="{% url 'industrial:re_confirm_email_code' %}" method="post">
                        {% csrf_token %}
                        Пожалуйста проверьте папку спам тоже! Если ещё не получили код подтверждения, можете запросить
                        заново.
                        <button class="btn btn-sm btn-dark">
                            Запросить код повторно
                        </button>
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        <h1>Ваша почта подтверждена</h1>
    {% endif %}
{% endblock %}

backend/industrial/templates/industrial/pages/dashboardapp.html
{% extends 'industrial/baseapp.html' %}
{% load static %}
{% load industrial_tags %}

{% block page_title %}Личный кабинет{% endblock %}


{% block page_content %}

<div class="container" style="margin-top: 5%;">
    <div class="row">
        {% if not content.app_inst.have_resume %}
        <div class="col-12 ">
            <h1>Добро пожаловать!</h1>
            <p class="pxp-text-light">Платформа Jobox - инструмент для размещения Ваших резюме.</p>
            <a href="{% url 'industrial:edit_summary' %}"><button class="btn btn-secondary">Создать новое резюме</button></a>
        </div>
    </div>
</div>
        {% else %}
            {% include 'industrial/components/summary.html' %}
        {% endif %}

{% endblock %}

backend/industrial/templates/industrial/pages/doc_2.html
{% extends 'industrial/base.html' %}
{% load static %}
{% load bulletin_board_tags %}


{% block page_content %}
    {% industrial_instruction %}
{% endblock %}

backend/industrial/templates/industrial/pages/enter_key.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block page_content %}
    <section class="pxp-hero vh-100" style="background-color: var(--pxpMainColorLight);">
        <div class="row align-items-center pxp-sign-hero-container">
            <div class="col-xl-6 pxp-column">
                <div class="pxp-sign-hero-fig text-center pb-100 pt-100">
                    <img src="{% static "industrial/images/signin-big-fig.png" %}" alt="Sign In">
                    <h1 class="mt-4 mt-lg-5">Добро пожаловать!</h1>
                </div>
            </div>
            <div class="col-xl-6 pxp-column pxp-is-light">
                <div class="pxp-sign-hero-form pb-100 pt-100">
                    <div class="row justify-content-center">
                        <div class="col-lg-6 col-xl-7 col-xxl-5">
                            <div class="pxp-sign-hero-form-content">

                                {% if wrong_key %}
                                    <h5 class="text-center text-danger ">Неверный код активации</h5>
                                    <br>
                                {% endif %}

                                <h5 class="text-center">На указанную вами почту отправлен код подтверждения</h5>
                                <form class="mt-4" method="post" action="{% url 'industrial:enter_key' %}">
                                    {% csrf_token %}
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="pxp-signin-page-email"
                                               placeholder="Email key" name="key">
                                        <label for="pxp-signin-page-email">Введите код подтверждения</label>
                                        <span class="fa fa-key"></span>
                                    </div>
                                    <button class="btn rounded-pill pxp-sign-hero-form-cta w-100">Восстановить пароль</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

backend/industrial/templates/industrial/pages/payment.html
{% extends "industrial/base.html" %}
{% block page_content %}


    <h1>Оплата</h1>
    <p class="pxp-text-light">$$$</p>



{% endblock %}

backend/industrial/templates/industrial/pages/signin.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block page_content %}
    <section class="pxp-hero vh-100" style="background-color: var(--pxpMainColorLight);">
        <div class="row align-items-center pxp-sign-hero-container">
            <div class="col-xl-6 pxp-column">
                <div class="pxp-sign-hero-fig text-center pb-100 pt-100">
                    <img src="{% static "industrial/" %}images/signin-big-fig.png" alt="Sign In">
                    <h1 class="mt-4 mt-lg-5">Добро пожаловать!</h1>
                </div>
            </div>
            <div class="col-xl-6 pxp-column pxp-is-light">
                <div class="pxp-sign-hero-form pb-100 pt-100">
                    <a class="text-center">Чтобы разместить Ваши вакансии необходимо</a>
                    <a style="margin-bottom: 50px;" class="text-center">войти в личный кабинет или зарегистрироватся!</a>
                    <div class="row justify-content-center">
                        <div class="col-lg-6 col-xl-7 col-xxl-5">
                            <div class="pxp-sign-hero-form-content">
                                {% if show_success_sign_up_message %}
                                    <h5 class="text-center text-success ">Готово! Можете авторизоваться</h5>
                                    <br>
                                    <br>
                                    <br>
                                {% endif %}

                                {% if sing_in_error %}
                                    <h5 class="text-center text-danger ">Ошибка авторизации!</h5>
                                    <br>
                                {% endif %}



                                <h5 class="text-center">Вход</h5>
                                <form class="mt-4" method="post" action="{% url 'industrial:sign_in' %}">
                                    {% csrf_token %}
                                    <div class="form-floating mb-3">
                                        <input type="email" class="form-control" id="pxp-signin-page-email"
                                               placeholder="Email address" name="email">
                                        <label for="pxp-signin-page-email">Введите e-mail</label>
                                        <span class="fa fa-envelope-o"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input type="password" class="form-control" id="pxp-signin-page-password"
                                               placeholder="Password" name="password">
                                        <label for="pxp-signin-page-password">Ваш пароль</label>
                                        <span class="fa fa-lock"></span>
                                    </div>
                                    <div class="text-center" style="margin-bottom: 5%;">
                                        <a href="#" class="password-control" onclick="return show_hide_pass(this);">Показать/Скрыть пароль</a><br>
                                    </div>
                                    <button href="submit" class="btn rounded-pill pxp-sign-hero-form-cta w-100">Вход
                                    </button>
                                    <div class="mt-4 text-center pxp-sign-hero-form-small">
                                        <a href="{% url 'industrial:forgot_password' %}" class="pxp-modal-link">Забыли пароль</a>
                                    </div>
                                    <div class="mt-4 text-center pxp-sign-hero-form-small">
                                        Еще нет аккаунта? <a
                                            href="{% url 'industrial:sign_up' %}">Зарегистрироваться</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<script src="{% static 'industrial/js/show_pass.js' %}"></script>
{% endblock %}

backend/industrial/templates/industrial/pages/signinapp.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block page_content %}
    <section class="pxp-hero vh-100" style="background-color: var(--pxpMainColorLight);">
        <div class="row align-items-center pxp-sign-hero-container">
            <div class="col-xl-6 pxp-column">
                <div class="pxp-sign-hero-fig text-center pb-100 pt-100">
                    <img src="{% static 'industrial/' %}images/signin-big-fig.png" alt="Sign In">
                    <h1 class="mt-4 mt-lg-5">Добро пожаловать!</h1>
                </div>
            </div>
            <div class="col-xl-6 pxp-column pxp-is-light">
                <div class="pxp-sign-hero-form pb-100 pt-100">
                    <a class="text-center">Чтобы разместить Ваше резюме необходимо</a>
                    <a style="margin-bottom: 50px;" class="text-center">войти в личный кабинет или зарегистрироватся!</a>
                    <div class="row justify-content-center">
                        <div class="col-lg-6 col-xl-7 col-xxl-5">
                            <div class="pxp-sign-hero-form-content">
                                {% if show_success_sign_up_message %}
                                    <h5 class="text-center text-success ">Готово! Можете авторизоваться</h5>
                                    <br>
                                    <br>
                                    <br>
                                {% endif %}

                                {% if sing_in_error %}
                                    <h5 class="text-center text-danger ">Ошибка авторизации!</h5>
                                    <br>
                                {% endif %}



                                <h5 class="text-center">Вход</h5>
                                <form class="mt-4" method="post" action="{% url 'industrial:sign_in_app' %}">
                                    {% csrf_token %}
                                    <div class="form-floating mb-3">
                                        <input type="email" class="form-control" id="pxp-signin-page-email"
                                               placeholder="Email address" name="email">
                                        <label for="pxp-signin-page-email">Введите e-mail</label>
                                        <span class="fa fa-envelope-o"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input type="password" class="form-control" id="pxp-signin-page-password"
                                               placeholder="Password" name="password">
                                        <label for="pxp-signin-page-password">Ваш пароль</label>
                                        <span class="fa fa-lock"></span>
                                    </div>
                                    <div class="text-center" style="margin-bottom: 5%;">
                                        <a href="#" class="password-control" onclick="return show_hide_pass(this);">Показать/Скрыть пароль</a><br>
                                    </div>

                                    <button href="submit" class="btn rounded-pill pxp-sign-hero-form-cta w-100">Вход
                                    </button>
                                    <div class="mt-4 text-center pxp-sign-hero-form-small">
                                        <a href="{% url 'industrial:forgot_password' %}" class="pxp-modal-link">Забыли пароль</a>
                                    </div>
                                    <div class="mt-4 text-center pxp-sign-hero-form-small">
                                        Еще нет аккаунта? <a
                                            href="{% url 'industrial:sign_up_app' %}">Зарегистрироваться</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<script src="{% static 'industrial/js/show_pass.js' %}"></script>
{% endblock %}

backend/industrial/templates/industrial/pages/signre.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block page_content %}
    <section class="pxp-hero vh-100" style="background-color: var(--pxpMainColorLight);">
        <div class="row align-items-center pxp-sign-hero-container">
            <div class="col-xl-6 pxp-column">
                <div class="pxp-sign-hero-fig text-center pb-100 pt-100">
                    <img src="{% static "industrial/images/signin-big-fig.png" %}" alt="Sign re">
                    <h1 class="mt-4 mt-lg-5">Добро пожаловать!</h1>
                </div>
            </div>
            <div class="col-xl-6 pxp-column pxp-is-light">
                <div class="pxp-sign-hero-form pb-100 pt-100">
                    <div class="row justify-content-center">
                        <div class="col-lg-6 col-xl-7 col-xxl-5">
                            <div class="pxp-sign-hero-form-content">

                                {% if sing_re_error %}
                                    <h5 class="text-center text-danger ">Ошибка ввода!</h5>
                                    <br>
                                {% endif %}

                                <h5 class="text-center">Сброс пароля</h5>
                                <form class="mt-4" method="post" action="{% url 'industrial:signre' %}">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{username}}" name="username">
                                    <div class="form-floating mb-3">
                                        <input type="password" class="form-control" id="pxp-signin-page-password"
                                               placeholder="Password1" name="password1">
                                        <label for="pxp-signin-page-password">Введите новый пароль</label>
                                        <span class="fa fa-lock"></span>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input type="password" class="form-control" id="pxp-signin-page-password"
                                               placeholder="Password2" name="password2">
                                        <label for="pxp-signin-page-password">Подтвердите пароль</label>
                                        <span class="fa fa-lock"></span>
                                    </div>
                                    <button href="submit" class="btn rounded-pill pxp-sign-hero-form-cta w-100">Сбросить пароль
                                    </button>
                                    <div class="mt-4 text-center pxp-sign-hero-form-small">
                                        <a href="{% url 'industrial:sign_in' %}" class="pxp-modal-link">Отменить сброс пароля</a>
                                    </div>
                                    <div class="mt-4 text-center pxp-sign-hero-form-small">
                                        <a href="{% url 'industrial:sign_up' %}">Зарегистрироваться</a>

                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}