backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers


from django.contrib.sitemaps.views import sitemap
from bulletin_board.sitemaps import JobSitemap, CompanySitemap, ApplicantSitemap, BlogSitemap, CustomSitemap

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bulletin_board.urls')),

    path('industrial/', include('industrial.urls')),

    path('payment/', include('payment.urls')),

    path('api/v1/', include(router.urls)),
    path('api-auth/',
         include('rest_framework.urls', namespace='rest_framework')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('sitemap.xml', sitemap, {
        'sitemaps': {
            "jobs": JobSitemap,
            "companies": CompanySitemap,
            "applicants": ApplicantSitemap,
            "blog": BlogSitemap,
            "custom": CustomSitemap
        }
    },
         name='django.contrib.sitemaps.views.sitemap')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page

from . import views

app_name = 'bulletin_board'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('for-company/', views.ForCompany.as_view(), name='for_company'),

    path('blog/', views.BlogList.as_view(), name='blog_list'),
    path('blog/<int:blog_id>', views.BlogView.as_view(), name='blog_view'),

    path('companies/', views.CompaniesList.as_view(), name='companies_list'),
    path('companies/<int:company_id>', views.CompanyView.as_view(), name='company_view'),

    path('orders/', views.JobsCatalog.as_view(), name='jobs_catalog'),
    path('orders/<int:job_id>/', views.JobView.as_view(), name='job_view'),
    path('orders/<int:job_id>/apply', csrf_exempt(views.ApplyJob.as_view()), name='apply_job'),

    path('summary/', views.SummaryCatalog.as_view(), name='sum_catalog'),
    path('summary/<int:sum_id>/', views.SummaryView.as_view(), name='sum_view'),

    path('application_to_admin', views.ApplicationToAdmin.as_view(), name='application_to_admin'),

    path('doc-1', views.Doc1.as_view(), name='doc_1'),
    path('doc-2', views.Doc2.as_view(), name='doc_2'),

    path('delete_education/',
         csrf_exempt(views.DeleteSummaryEducation.as_view()),
         name='delete_education'),

    path('delete_experience/',
         csrf_exempt(views.DeleteSummaryExperience.as_view()),
         name='delete_experience'),

    path('robots.txt', views.get_robots_txt, name='robots_txt'),
    # path('sitemap.xml', views.get_sitemap_xml, name='sitemap_xml')
]

backend/drf/urls.py
# from django.contrib import admin
# from django.urls import path
# from . import views
# from django.views.decorators.csrf import csrf_exempt
#
# app_name = "drf"
#
# urlpatterns = [
#     path('dashboardapp_api/', csrf_exempt(views.DashboardAppAPI.as_view()),
#          name='dashboardapp_api'),
# ]

backend/industrial/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "industrial"

urlpatterns = [

    path('admin/request/publish_job_<int:job_id>',
         views.AdminPublishJob.as_view(), name='admin_publish_job'),
    path('admin/request/reject_job_<int:job_id>',
         views.AdminRejectJob.as_view(), name='admin_reject_job'),
    path('admin/request/close_job_<int:job_id>', views.AdminCloseJob.as_view(),
         name='admin_close_job'),

    path('reg-<str:user_ref_code>/', views.RefLinkView.as_view(),
         name='ref_link_view'),

    path('signin/', views.SignInView.as_view(), name='sign_in'),
    path('signinapp/', views.SignInAppView.as_view(), name='sign_in_app'),
    path('signupapp/', views.SignUpAppView.as_view(), name='sign_up_app'),
    path('get_company/', csrf_exempt(views.GetCompanyByInn.as_view()),
         name='get_company_by_inn'),

    path('signup/', views.SignUpView.as_view(), name='sign_up'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('confirm_email/', views.ConfirmEmailView.as_view(),
         name='confirm_email'),  # Поддтвержденые почты

    path('confirm_email_app/', views.ConfirmEmailAppView.as_view(),
         name='confirm_emailapp'),

    path('confirm_email/send_again',
         views.ResendConfirmEmailCodeView.as_view(),
         name='re_confirm_email_code'),  # Поддтвержденые почты

    path('confirm_email/send_againapp',
         views.ResendConfirmEmailCodeAppView.as_view(),
         name='re_confirm_email_codeapp'),  # Поддтвержденые почты

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

    path('dashboardapp/', views.DashboardAPP.as_view(), name='dashboardapp'),

    path('summary/', csrf_exempt(views.Summary.as_view()),
         name='summary'),

    path('edit_summary/', csrf_exempt(views.EditSummary.as_view()),
         name='edit_summary'),

    path('edit_summary/education/',
         csrf_exempt(views.EditSummaryEducation.as_view()),
         name='education'),

    path('edit_summary/experience/',
         csrf_exempt(views.EditSummaryExperience.as_view()),
         name='experience'),

    path('delete_tags/',
         csrf_exempt(views.TagsAPI.as_view()),
         name='delete_tags'),

    # path('delete_summary/education/',
    #      csrf_exempt(views.DeleteSummaryEducation.as_view()),
    #      name='delete_education'),
    #
    # path('delete_summary/experience/',
    #      csrf_exempt(views.DeleteSummaryExperience.as_view()),
    #      name='delete_experience'),

    path('profile/', views.Profile.as_view(), name='profile'),

    path('profile/edit_brand_info/', views.ProfileEditBrandInfo.as_view(),
         name='edit_brand_info'),

    path('profile/edit_administrator_info/',
         views.ProfileEditAdministratorInfo.as_view(),
         name='edit_administrator_info'),

    path('profile/edit_company_description/',
         views.ProfileEditCompanyDescription.as_view(),
         name='edit_company_description'),

    path('profile/edit_user_password/',
         views.ProfileEditUserPassword.as_view(), name='edit_user_password'),

    path('jobs/new', csrf_exempt(views.AddNewJob.as_view()), name='add_new_job'),
    path('jobs/list', csrf_exempt(views.JobsList.as_view()), name='jobs_list'),

    path('jobs/list_api', csrf_exempt(views.JobListAPI.as_view()),
         name='jobs_list_api'),
    path('jobs/pay_for_job_api', csrf_exempt(views.PayForJobAPI.as_view()),
         name='pay_for_job_api'),

    path('jobs/<int:job_id>/edit', csrf_exempt(views.EditJob.as_view()), name='edit_job'),
    path('jobs/<int:job_id>/view', views.ViewJob.as_view(), name='view_job'),
    path('jobs/<int:job_id>/delete', views.DeleteJob.as_view(),
         name='delete_job'),

    path('candidates/<int:resp_id>/delete', views.DeleteResponse.as_view(),
         name='delete_resp'),

    path('candidates/', views.CandidatesList.as_view(), name='candidates'),

    path('payment/', views.Payment.as_view(), name='payment'),

    path('user_agreement/', views.UserAgreement.as_view(),
         name='user_agreement'),
    path('instruction/', views.Instruction.as_view(), name='instruction'),
    path('support/', views.Support.as_view(), name='support'),

    path('user_agreementapp/', views.UserAgreementApp.as_view(),
         name='user_agreementapp'),
    path('instructionapp/', views.InstructionApp.as_view(), name='instructionapp'),
    path('supportapp/', views.SupportApp.as_view(), name='supportapp'),


    path('finance/', views.Finance.as_view(), name='finance'),

    path('payment_invoices/', views.PaymentInvoices.as_view(),
         name='payment_invoices'),

    path('payment_invoices/', views.PaymentInvoice.as_view(),
         name='payment_invoice'),
    path('payment_invoices/<int:invoice_id>/', views.PaymentInvoice.as_view(),
         name='payment_invoice'),
    path('payment_invoices/<int:invoice_id>/check',
         views.PaymentInvoiceCheck.as_view(), name='payment_invoice_check'),

    path('forgot_password/', views.ForgotPasswordView.as_view(),
         name='forgot_password'),
    path('enter_key/', views.EnterKeyView.as_view(),
         name='enter_key'),
    path('signre/', views.SignReView.as_view(), name='signre'),

]

backend/bulletin_board/models.py
from django.db import models


class TemplateParts(models.Model):
    """Части шаблонов """

    name = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    content = models.TextField(max_length=50000)

    class Meta:
        verbose_name = "Части шаблонов"
        verbose_name_plural = "Часть шаблона"


class SocialLink(models.Model):
    """Социальные ссылки """

    name = models.CharField(max_length=150)
    url = models.CharField(max_length=150)
    icon_code = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Social links"
        verbose_name_plural = "Social links"


class IndexFile(models.Model):
    name = models.CharField(max_length=150)
    content = models.TextField(max_length=50000)


class SeoMeta(models.Model):
    meta_type = models.CharField(
        max_length=20,
        choices=(
            ("title", "title"),
            ("description", "description"),
            ("keywords", "keywords"),
            ("image", "image")
        )
    )
    path = models.CharField(max_length=150)
    content = models.TextField(max_length=50000)
    image = models.FileField(upload_to='meta_images', null=True, blank=True)

backend/bulletin_board/templates/bulletin_board/pages/blog_list.html
{% extends 'bulletin_board/base.html' %}
{% load static %}

{% block page_content %}
    <section>
        <div class="pxp-container">
            <div class="row justify-content-center">
                <div class="col-xl-9">
                    <div class="pxp-blog-hero">
                        <h1 class="text-center">PRO-РАБОТУ</h1>
                        <div class="pxp-hero-subtitle pxp-text-light text-center">статьи, новости, акции из мира HR
                        </div>
                    </div>


                    <div class="mt-4 mt-lg-5">
                        <div class="row">
                            {% for blog in blogs_list %}
                                <div class="col-md-6 col-xxl-4 pxp-posts-card-1-container">
                                    <div class="pxp-posts-card-1 pxp-has-border">
                                        <div class="pxp-posts-card-1-top">
                                            <div class="pxp-posts-card-1-top-bg">
                                                <div class="pxp-posts-card-1-image pxp-cover"
                                                     style="background-image: url({{ blog.main_image.url }});"></div>
                                                <div class="pxp-posts-card-1-info">
                                                    <div class="pxp-posts-card-1-date">{{ blog.created_at }}</div>

                                                    <a
                                                            href="{% url "bulletin_board:blog_view" blog_id=blog.id %}"
                                                            class="pxp-posts-card-1-category"
                                                    >{{ blog.category.title }}</a>
                                                </div>
                                            </div>
                                            <div class="pxp-posts-card-1-content">
                                                <a
                                                        href="{% url "bulletin_board:blog_view" blog_id=blog.id %}"
                                                        class="pxp-posts-card-1-title"
                                                >
                                                    {{ blog.title }}
                                                </a>
                                                <div class="pxp-posts-card-1-summary pxp-text-light">
                                                    {{ blog.subtitle }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="pxp-posts-card-1-bottom">
                                            <div class="pxp-posts-card-1-cta">
                                                <a
                                                        href="{% url "bulletin_board:blog_view" blog_id=blog.id %}"
                                                >
                                                    Узнать больше
                                                    <span class="fa fa-angle-right"></span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>

{#                        <div class="row mt-4 mt-lg-5 justify-content-between align-items-center">#}
{#                            <div class="col-auto">#}
{#                                <nav class="mt-3 mt-sm-0" aria-label="Blog articles pagination">#}
{#                                    <ul class="pagination pxp-pagination">#}
{#                                        <li class="page-item active" aria-current="page">#}
{#                                            <span class="page-link">1</span>#}
{#                                        </li>#}
{#                                        <li class="page-item"><a class="page-link" href="#">2</a></li>#}
{#                                        <li class="page-item"><a class="page-link" href="#">3</a></li>#}
{#                                    </ul>#}
{#                                </nav>#}
{#                            </div>#}
                            <div class="col-auto">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

backend/bulletin_board/templates/bulletin_board/pages/companies_list.html
{% extends 'bulletin_board/base.html' %}
{% load static %}
{% load core_tags %}

{% block page_content %}
    <section class="pxp-page-header-simple">
        <div class="pxp-container">
            <h1>Каталог компаний</h1>
            <div class="pxp-hero-subtitle pxp-text-ligh">В нашей базе представлены только проверенные юр. лица</div>
            <div class="pxp-hero-form pxp-hero-form-round pxp-large mt-3 mt-lg-4 pxp-has-border">

                <form class="row gx-3 align-items-center" id="search_form">
                    <input type="hidden" name="page" id="pagination_current_page">

                    <div class="col-12 col-lg">
                        <div class="input-group mb-3 mb-lg-0">
                            <span class="input-group-text">
                                <span class="fa fa-search"></span>
                            </span>
                            <input
                                    type="text"
                                    class="form-control"
                                    placeholder="Введите название компании"
                                    name="name"
                                    value="{{ rq.name }}"
                            >
                        </div>
                    </div>


                    <div class="col-12 col-lg-auto">
                        <button type="submit">Найти</button>
                    </div>
                </form>

            </div>
        </div>
    </section>

    <section class="mt-4 mt-lg-5 pt-100 pb-100" style="background-color: var(--pxpMainColorLight);">
        <div class="pxp-container">
            <div class="pxp-jobs-list-top">
                <div class="row justify-content-between align-items-center">
                    <div class="col-auto">
                        <h2>
                            <span class="pxp-text-light">Всего</span>
                            {{ companies_count }}
                            <span class="pxp-text-light">компаний</span>
                        </h2>
                    </div>

                </div>
            </div>

            <div class="row">

                {% for company in companies_list %}

                {% if company.jobs_count != 0 %}

                    <div class="col-md-6 col-xl-4 col-xxl-3 pxp-companies-card-1-container" style="word-wrap: break-word">
                        <div class="pxp-companies-card-1 pxp-has-shadow">
                            <div class="pxp-companies-card-1-top">

                                <a
                                        href="{% url 'bulletin_board:company_view' company_id=company.id %}"
                                        class="pxp-companies-card-1-company-logo"

                                        {% if company.brand_logo %}
                                        style="background-image: url({{ company.brand_logo.url }});"
                                        {% else %}
                                        style="background-image: url({% system_image_company_default_logo_url %});"
                                        {% endif %}

                                ></a>
                                <a
                                        href="{% url 'bulletin_board:company_view' company_id=company.id %}"
                                        class="pxp-companies-card-1-company-name">
                                    {{ company.name }}
                                </a>
                                <div class="pxp-companies-card-1-company-description pxp-text-light">
                                    {{ company.company_description | slice:":200" }}...
                                </div>
                            </div>
                            <div class="pxp-companies-card-1-bottom">
                                <a
                                        href="{% url 'bulletin_board:company_view' company_id=company.id %}"
                                        class="pxp-companies-card-1-company-jobs"
                                >
                                    {{ company.jobs_count }} вакансий
                                </a>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% endfor %}

            </div>

            <div class="row mt-4 mt-lg-5 justify-content-between align-items-center">
                <div class="col-auto">

                    <nav class="mt-3 mt-sm-0" aria-label="Jobs list pagination">
                        <ul class="pagination pxp-pagination">
                            {% for pagination_page in rq.pagination_range %}
                                {% if pagination_page > 0 %}
                                    <li
                                            class="page-item {% if pagination_page == rq.page %}active{% endif %}"
                                            aria-current="page"
                                            onclick="document.getElementById('pagination_current_page').value={{ pagination_page }};document.getElementById('search_form').submit()"
                                    >
                                        <span class="page-link">{{ pagination_page }}</span>
                                    </li>
                                {% endif %}
                            {% endfor %}


                        </ul>
                    </nav>


                </div>

            </div>
        </div>
    </section>
{% endblock %}

backend/bulletin_board/templates/bulletin_board/pages/doc_1.html
{% extends "bulletin_board/base.html" %}
{% load bulletin_board_tags %}

{% block page_content %}
    {% doc_1_body %}
{% endblock %}

backend/bulletin_board/templates/bulletin_board/pages/for_company.html
{% extends 'bulletin_board/base.html' %}
{% load static %}
{% load industrial_tags %}
{% load bulletin_board_tags %}
{% load cache %}

{% block page_content %}
    {% cache 1200 for_company_page_content_cache %}
        <section>
            <div class="pxp-container">
                <div class="row justify-content-center">
                    <div class="col-xl-9">
                        <div class="pxp-blog-hero">
                            <h1 class="text-center"><span style="color: var(--pxpMainColor)">Jobox</span><br>выбирай то,
                                что
                                работает за тебя</h1>
                            <div class="pxp-hero-subtitle pxp-text-light text-center">Удобная, интуитивно-понятная
                                платформа
                                для
                                поиска соискателей
                            </div>
                        </div>

                        <div id="pxp-blog-featured-posts-carousel"
                             class="carousel slide carousel-fade pxp-blog-featured-posts-carousel"
                             data-bs-ride="carousel">
                            <div class="carousel-inner">

                                {% for slider_blog in slider_blogs %}
                                    <div
                                        class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}"
                                    >
                                        <div class="pxp-featured-posts-item pxp-cover"
                                             style="background-image: url({{ slider_blog.main_image.url }});">
                                            <div class="pxp-hero-opacity"></div>
                                            <div class="pxp-featured-posts-item-caption">
                                                <div class="pxp-featured-posts-item-caption-content">
                                                    <div class="row align-content-center justify-content-center">
                                                        <div class="col-9 col-md-8 col-xl-7 col-xxl-6">
                                                            <div class="pxp-featured-posts-item-date">{{ slider_blog.category.title }}</div>
                                                            <div class="pxp-featured-posts-item-title">
                                                                {{ slider_blog.title }}
                                                            </div>
                                                            <div class="pxp-featured-posts-item-summary pxp-text-light mt-2">
                                                                {{ slider_blog.subtitle }}
                                                            </div>
                                                            <div class="mt-4 mt-md-5 text-center">
                                                                {% if slider_blog.show_sing_in_on_company_page %}
                                                                    <a href="{% url "industrial:sign_in" %}"
                                                                       class="btn rounded-pill pxp-section-cta">
                                                                        Вход в личный кабинет
                                                                    </a>
                                                                {% else %}
                                                                    <a href="{% url "bulletin_board:blog_view" blog_id=slider_blog.id %}"
                                                                       class="btn rounded-pill pxp-section-cta">
                                                                        Подробнее
                                                                    </a>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                            <button class="carousel-control-prev" type="button"
                                    data-bs-target="#pxp-blog-featured-posts-carousel" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button"
                                    data-bs-target="#pxp-blog-featured-posts-carousel" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% for_company_template_part_1 %}

        <section class="pt-100 pb-100" style="background-color: var(--pxpMainColorLight);">
            <div class="pxp-container">
                <h2 class="pxp-section-h2">Компании</h2>
                <p class="pxp-text-light">только проверенные контрагенты</p>

                <div class="row mt-4 mt-md-5 pxp-animate-in pxp-animate-in-top" style="word-wrap: break-word;">
                    {% recomended_companies_list %}
                </div>

                <div class="mt-4 mt-md-5 pxp-animate-in pxp-animate-in-top">
                    <a
                            href="{% url "bulletin_board:companies_list" %}"
                            class="btn rounded-pill pxp-section-cta">
                        Все компании <span class="fa fa-angle-right"></span>
                    </a>
                </div>
            </div>
        </section>

        <section class="mt-100">
            <div class="pxp-container">
                <h2 class="pxp-section-h2">Новости</h2>
                <p class="pxp-text-light">всегда актуальные вести из мира HR</p>

                <div class="row mt-4 mt-md-5 pxp-animate-in pxp-animate-in-top" style="word-wrap: break-word;">
                    {% recomended_blogs_list %}
                </div>

                <div class="mt-4 mt-md-5 pxp-animate-in pxp-animate-in-top">
                    <a href="{% url "bulletin_board:blog_list" %}" class="btn rounded-pill pxp-section-cta">
                        Показать все статьи<span class="fa fa-angle-right"></span>
                    </a>
                </div>
            </div>
        </section>
        <section class="mt-100 pxp-no-hero">
            <div class="pxp-container">
{#                <h2 class="pxp-section-h2 text-center">Наши контакты</h2>#}
{#                <p class="pxp-text-light text-center">Будем рады Вам в любое время</p>#}
{##}
{#                <div class="row mt-4 mt-md-5 justify-content-center pxp-animate-in pxp-animate-in-top pxp-in">#}
{#                    >#}
{#                    <div class="col-lg-4 col-xxl-3 pxp-contact-card-1-container">#}
{#                        <a href="#" class="pxp-contact-card-1">#}
{#                            <div class="pxp-contact-card-1-icon-container">#}
{#                                <div class="pxp-contact-card-1-icon">#}
{#                                    <span class="fa fa-phone"></span>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="pxp-contact-card-1-title">8-800-700-33-21</div>#}
{#                        </a>#}
{#                    </div>#}
{#                    <div class="col-lg-4 col-xxl-3 pxp-contact-card-1-container">#}
{#                        <a href="#" class="pxp-contact-card-1">#}
{#                            <div class="pxp-contact-card-1-icon-container">#}
{#                                <div class="pxp-contact-card-1-icon">#}
{#                                    <span class="fa fa-envelope-o"></span>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="pxp-contact-card-1-title">manager@rostjob.ru</div>#}
{#                        </a>#}
{#                    </div>#}
{#                </div>#}

                <div class="row mt-100 justify-content-center pxp-animate-in pxp-animate-in-top pxp-in">
                    <div class="col-lg-6 col-xxl-4">
                        <div class="pxp-contact-us-form pxp-has-animation pxp-animate">
                            <h2 class="pxp-section-h2 text-center">Оставить заявку</h2>
                            <form class="mt-4" action="{% url 'bulletin_board:application_to_admin' %}" method="post">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="contact-us-name" class="form-label">Имя</label>
                                    <input
                                            type="text"
                                            class="form-control"
                                            id="contact-us-name"
                                            placeholder="Введите Ваше имя"
                                            name="name"
                                    >
                                </div>
                                <div class="mb-3">
                                    <label for="contact-us-email" class="form-label">Email</label>
                                    <input
                                            type="text"
                                            class="form-control"
                                            id="contact-us-email"
                                            placeholder="Введите почту для связи с Вами"
                                            name="email"
                                    >
                                </div>
                                <div class="mb-3">
                                    <label for="contact-us-message" class="form-label">Сообщение</label>
                                    <textarea
                                            class="form-control"
                                            id="contact-us-message"
                                            placeholder="Что вас заинтересовало?"
                                            name="text"
                                    ></textarea>
                                </div>
                                <button type="submit" class="btn rounded-pill pxp-section-cta d-block w-100">
                                    Отправить
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endcache %}
{% endblock %}