backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers


from django.contrib.sitemaps.views import sitemap
from bulletin_board.sitemaps import JobSitemap, CompanySitemap, ApplicantSitemap, BlogSitemap, CustomSitemap

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bulletin_board.urls')),

    path('industrial/', include('industrial.urls')),

    path('payment/', include('payment.urls')),

    path('api/v1/', include(router.urls)),
    path('api-auth/',
         include('rest_framework.urls', namespace='rest_framework')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('sitemap.xml', sitemap, {
        'sitemaps': {
            "jobs": JobSitemap,
            "companies": CompanySitemap,
            "applicants": ApplicantSitemap,
            "blog": BlogSitemap,
            "custom": CustomSitemap
        }
    },
         name='django.contrib.sitemaps.views.sitemap')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page

from . import views

app_name = 'bulletin_board'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('for-company/', views.ForCompany.as_view(), name='for_company'),

    path('blog/', views.BlogList.as_view(), name='blog_list'),
    path('blog/<int:blog_id>', views.BlogView.as_view(), name='blog_view'),

    path('companies/', views.CompaniesList.as_view(), name='companies_list'),
    path('companies/<int:company_id>', views.CompanyView.as_view(), name='company_view'),

    path('orders/', views.JobsCatalog.as_view(), name='jobs_catalog'),
    path('orders/<int:job_id>/', views.JobView.as_view(), name='job_view'),
    path('orders/<int:job_id>/apply', csrf_exempt(views.ApplyJob.as_view()), name='apply_job'),

    path('summary/', views.SummaryCatalog.as_view(), name='sum_catalog'),
    path('summary/<int:sum_id>/', views.SummaryView.as_view(), name='sum_view'),

    path('application_to_admin', views.ApplicationToAdmin.as_view(), name='application_to_admin'),

    path('doc-1', views.Doc1.as_view(), name='doc_1'),
    path('doc-2', views.Doc2.as_view(), name='doc_2'),

    path('delete_education/',
         csrf_exempt(views.DeleteSummaryEducation.as_view()),
         name='delete_education'),

    path('delete_experience/',
         csrf_exempt(views.DeleteSummaryExperience.as_view()),
         name='delete_experience'),

    path('robots.txt', views.get_robots_txt, name='robots_txt'),
    # path('sitemap.xml', views.get_sitemap_xml, name='sitemap_xml')
]

backend/drf/urls.py
# from django.contrib import admin
# from django.urls import path
# from . import views
# from django.views.decorators.csrf import csrf_exempt
#
# app_name = "drf"
#
# urlpatterns = [
#     path('dashboardapp_api/', csrf_exempt(views.DashboardAppAPI.as_view()),
#          name='dashboardapp_api'),
# ]

backend/industrial/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "industrial"

urlpatterns = [

    path('admin/request/publish_job_<int:job_id>',
         views.AdminPublishJob.as_view(), name='admin_publish_job'),
    path('admin/request/reject_job_<int:job_id>',
         views.AdminRejectJob.as_view(), name='admin_reject_job'),
    path('admin/request/close_job_<int:job_id>', views.AdminCloseJob.as_view(),
         name='admin_close_job'),

    path('reg-<str:user_ref_code>/', views.RefLinkView.as_view(),
         name='ref_link_view'),

    path('signin/', views.SignInView.as_view(), name='sign_in'),
    path('signinapp/', views.SignInAppView.as_view(), name='sign_in_app'),
    path('signupapp/', views.SignUpAppView.as_view(), name='sign_up_app'),
    path('get_company/', csrf_exempt(views.GetCompanyByInn.as_view()),
         name='get_company_by_inn'),

    path('signup/', views.SignUpView.as_view(), name='sign_up'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('confirm_email/', views.ConfirmEmailView.as_view(),
         name='confirm_email'),  # Поддтвержденые почты

    path('confirm_email_app/', views.ConfirmEmailAppView.as_view(),
         name='confirm_emailapp'),

    path('confirm_email/send_again',
         views.ResendConfirmEmailCodeView.as_view(),
         name='re_confirm_email_code'),  # Поддтвержденые почты

    path('confirm_email/send_againapp',
         views.ResendConfirmEmailCodeAppView.as_view(),
         name='re_confirm_email_codeapp'),  # Поддтвержденые почты

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

    path('dashboardapp/', views.DashboardAPP.as_view(), name='dashboardapp'),

    path('summary/', csrf_exempt(views.Summary.as_view()),
         name='summary'),

    path('edit_summary/', csrf_exempt(views.EditSummary.as_view()),
         name='edit_summary'),

    path('edit_summary/education/',
         csrf_exempt(views.EditSummaryEducation.as_view()),
         name='education'),

    path('edit_summary/experience/',
         csrf_exempt(views.EditSummaryExperience.as_view()),
         name='experience'),

    path('delete_tags/',
         csrf_exempt(views.TagsAPI.as_view()),
         name='delete_tags'),

    # path('delete_summary/education/',
    #      csrf_exempt(views.DeleteSummaryEducation.as_view()),
    #      name='delete_education'),
    #
    # path('delete_summary/experience/',
    #      csrf_exempt(views.DeleteSummaryExperience.as_view()),
    #      name='delete_experience'),

    path('profile/', views.Profile.as_view(), name='profile'),

    path('profile/edit_brand_info/', views.ProfileEditBrandInfo.as_view(),
         name='edit_brand_info'),

    path('profile/edit_administrator_info/',
         views.ProfileEditAdministratorInfo.as_view(),
         name='edit_administrator_info'),

    path('profile/edit_company_description/',
         views.ProfileEditCompanyDescription.as_view(),
         name='edit_company_description'),

    path('profile/edit_user_password/',
         views.ProfileEditUserPassword.as_view(), name='edit_user_password'),

    path('jobs/new', csrf_exempt(views.AddNewJob.as_view()), name='add_new_job'),
    path('jobs/list', csrf_exempt(views.JobsList.as_view()), name='jobs_list'),

    path('jobs/list_api', csrf_exempt(views.JobListAPI.as_view()),
         name='jobs_list_api'),
    path('jobs/pay_for_job_api', csrf_exempt(views.PayForJobAPI.as_view()),
         name='pay_for_job_api'),

    path('jobs/<int:job_id>/edit', csrf_exempt(views.EditJob.as_view()), name='edit_job'),
    path('jobs/<int:job_id>/view', views.ViewJob.as_view(), name='view_job'),
    path('jobs/<int:job_id>/delete', views.DeleteJob.as_view(),
         name='delete_job'),

    path('candidates/<int:resp_id>/delete', views.DeleteResponse.as_view(),
         name='delete_resp'),

    path('candidates/', views.CandidatesList.as_view(), name='candidates'),

    path('payment/', views.Payment.as_view(), name='payment'),

    path('user_agreement/', views.UserAgreement.as_view(),
         name='user_agreement'),
    path('instruction/', views.Instruction.as_view(), name='instruction'),
    path('support/', views.Support.as_view(), name='support'),

    path('user_agreementapp/', views.UserAgreementApp.as_view(),
         name='user_agreementapp'),
    path('instructionapp/', views.InstructionApp.as_view(), name='instructionapp'),
    path('supportapp/', views.SupportApp.as_view(), name='supportapp'),


    path('finance/', views.Finance.as_view(), name='finance'),

    path('payment_invoices/', views.PaymentInvoices.as_view(),
         name='payment_invoices'),

    path('payment_invoices/', views.PaymentInvoice.as_view(),
         name='payment_invoice'),
    path('payment_invoices/<int:invoice_id>/', views.PaymentInvoice.as_view(),
         name='payment_invoice'),
    path('payment_invoices/<int:invoice_id>/check',
         views.PaymentInvoiceCheck.as_view(), name='payment_invoice_check'),

    path('forgot_password/', views.ForgotPasswordView.as_view(),
         name='forgot_password'),
    path('enter_key/', views.EnterKeyView.as_view(),
         name='enter_key'),
    path('signre/', views.SignReView.as_view(), name='signre'),

]

backend/bulletin_board/models.py
from django.db import models


class TemplateParts(models.Model):
    """Части шаблонов """

    name = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    content = models.TextField(max_length=50000)

    class Meta:
        verbose_name = "Части шаблонов"
        verbose_name_plural = "Часть шаблона"


class SocialLink(models.Model):
    """Социальные ссылки """

    name = models.CharField(max_length=150)
    url = models.CharField(max_length=150)
    icon_code = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Social links"
        verbose_name_plural = "Social links"


class IndexFile(models.Model):
    name = models.CharField(max_length=150)
    content = models.TextField(max_length=50000)


class SeoMeta(models.Model):
    meta_type = models.CharField(
        max_length=20,
        choices=(
            ("title", "title"),
            ("description", "description"),
            ("keywords", "keywords"),
            ("image", "image")
        )
    )
    path = models.CharField(max_length=150)
    content = models.TextField(max_length=50000)
    image = models.FileField(upload_to='meta_images', null=True, blank=True)

backend/bulletin_board/templates/bulletin_board/components/app_table.html
{% if content.app_inst.have_tabel %}
<table class="table">
    {% if content.app_inst.have_experience %}
    <thead>
        <tr>
            <th>Организация</th>
            <th>Должность</th>
            <th colspan="2" >Обязанности</th>
            <th>Период работы</th>
        </tr>
    </thead>
    {% for inst in content.experience_inst %}
    <tbody>
        <tr>
            <td>{{ inst.name }}</td>
            <td>{{ inst.position }}</td>
            <td colspan="2" >{{ inst.function }}</td>
            <td>{{ inst.start_data|date:"d.m.Y" }} - {{ inst.end_data|date:"d.m.Y"}}</td>
        </tr>
    </tbody>
    {% endfor %}
    {% endif %}
    {% if content.app_inst.have_education %}
    <thead>
        <tr>
            <th>Учебное заведение</th>
            <th>Факультет</th>
            <th>Специальность</th>
            <th>Уровень образования</th>
            <th>Период обучения</th>
        </tr>
    </thead>
    {% for inst in content.education_inst %}
    <tbody>
        <tr>
            <td>{{ inst.name }}</td>
            <td>{{ inst.faculty }}</td>
            <td>{{ inst.specialization }}</td>
            <td>{{ inst.level }}</td>
            <td>{{ inst.start_data|date:"d.m.Y" }}-{{ inst.end_data|date:"d.m.Y" }}</td>
        </tr>
    </tbody>
    {% endfor %}
    {% endif %}
</table>
{% endif %}


<style>
.table {
	width: 100%;
	margin-bottom: 20px;
	border: 2px solid #dddddd;
	border-collapse: collapse;

}

.table th {
	font-weight: bold;
	padding: 5px;
	background: #efefef;
	border: 2px solid #dddddd;
}

.table td {
	border: 2px solid #dddddd;
	padding: 5px;
}

</style>

backend/bulletin_board/templates/bulletin_board/components/page_custom_metas.html
{% if title %}
    <meta name="title" content="{{ title }}"/>
    <meta name="og:title" content="{{ title }}"/>
{% endif %}

{% if description %}
    <meta name="description" content="{{ description }}"/>
    <meta name="og:description" content="{{ description }}"/>
{% endif %}

{% if keywords %}
    <meta name="keywords" content="{{ keywords }}"/>
    <meta name="og:keywords" content="{{ keywords }}"/>
{% endif %}


{% if image %}
    <meta name="og:image" content="{{ image.url }}">
{% endif %}

backend/bulletin_board/templates/bulletin_board/components/recomended_blogs.html
{% load cache %}
{% load static %}
{% cache 1200 recomended_blogs %}
    {% for blog in recomended_blogs %}
        <div class="col-md-6 col-xl-4 col-xxl-3 pxp-posts-card-1-container">
            <div class="pxp-posts-card-1 pxp-has-border">
                <div class="pxp-posts-card-1-top">
                    <div class="pxp-posts-card-1-top-bg">
                        <div
                                class="pxp-posts-card-1-image pxp-cover"
                                style="background-image: url({{ blog.main_image.url }});"
                        ></div>
                        <div class="pxp-posts-card-1-info">
                            <div class="pxp-posts-card-1-date">
                                {{ blog.created_at }}
                            </div>
                            <a
                                    href="{% url "bulletin_board:blog_view" blog_id=blog.id %}"
                                    class="pxp-posts-card-1-category">
                                {{ blog.category.title }}
                            </a>
                        </div>
                    </div>
                    <div class="pxp-posts-card-1-content">
                        <a
                                href="{% url "bulletin_board:blog_view" blog_id=blog.id %}"
                                class="pxp-posts-card-1-title"
                        >
                            {{ blog.title }}
                        </a>
                        <div class="pxp-posts-card-1-summary pxp-text-light">
                            {{ blog.subtitle }}
                        </div>
                    </div>
                </div>
                <div class="pxp-posts-card-1-bottom">
                    <div class="pxp-posts-card-1-cta">
                        <a
                                href="{% url "bulletin_board:blog_view" blog_id=blog.id %}"
                        >
                            Узнать больше
                            <span class="fa fa-angle-right"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endcache %}

backend/bulletin_board/templates/bulletin_board/components/recomended_companies.html
{% load static %}
{% load core_tags %}
{% for company in companies %}
    <div class="col-md-6 col-xl-4 col-xxl-3 pxp-companies-card-1-container">
        <div class="pxp-companies-card-1 pxp-has-shadow">
            <div class="pxp-companies-card-1-top">
                <a
                        href="{% url "bulletin_board:company_view"  company_id=company.id %}"
                        class="pxp-companies-card-1-company-logo"
                        {% if company.brand_logo %}
                        style="background-image: url({{ company.brand_logo.url }});"
                        {% else %}
                        style="background-image: url({% system_image_company_default_logo_url %}"></a>
                        {% endif %}
                >

                </a>

                <a
                        href="{% url "bulletin_board:company_view"  company_id=company.id %}"
                        class="pxp-companies-card-1-company-name"
                >
                    {{ company.name }}
                </a>
                <div class="pxp-companies-card-1-company-description pxp-text-light">
                    {{ company.company_description | slice:":200" }}..
                </div>
            </div>
            <div class="pxp-companies-card-1-bottom">
                <a
                        href="{% url "bulletin_board:company_view"  company_id=company.id %}"
                        class="pxp-companies-card-1-company-jobs"
                >
                    {{ company.published_jobs }} вакансий
                </a>
            </div>
        </div>
    </div>
{% endfor %}

backend/bulletin_board/templates/bulletin_board/components/recomended_jobs.html
{% load static %}
{% load core_tags %}

{% for job in recomended_jobs %}
    <div class="col-md-6 col-xl-4 col-xxl-3 pxp-jobs-card-1-container">
        <div class="pxp-jobs-card-1 pxp-has-border">
            <div class="pxp-jobs-card-1-top">
                <a
                        href="{% url "bulletin_board:jobs_catalog" %}?category={{ job.category.id }}"
                        class="pxp-jobs-card-1-category"
                >
                    <div class="pxp-jobs-card-1-category-icon">
                        <span class="{{ job.category.icon_code }}"></span>
                    </div>
                    <div class="pxp-jobs-card-1-category-label">{{ job.category.title }}</div>
                </a>
                <a
                        href="{% url "bulletin_board:job_view" job_id=job.id %}"
                        class="pxp-jobs-card-1-title"
                >
                    {{ job.title }} {{ job.qualification }}
                </a>
                <div class="pxp-jobs-card-1-details">
                    <a
                            href="{% url "bulletin_board:jobs_catalog" %}?location={{ job.location.id }}"
                            class="pxp-jobs-card-1-location"
                    >
                        <span class="fa fa-globe"></span>
                        {{ job.location.city }}
                    </a>
                    <div class="pxp-jobs-card-1-type">
                        {{ job.employment_type.title }}
                    </div>
                </div>
                <div class="pxp-jobs-card-1-details">
                    <a href="#" class="pxp-jobs-card-1-location">
                        <span class="fa fa-money"></span>
                        {{ job.salary }} руб.
                    </a>
                    <div class="pxp-jobs-card-1-type">
                        {{ job.salary_condition.title }}
                    </div>
                </div>
            </div>
            <div class="pxp-jobs-card-1-bottom">
                <div class="pxp-jobs-card-1-bottom-left">
                    <div class="pxp-jobs-card-1-date pxp-text-light">от {{ job.published_at }}</div>
                    <a href="{% url "bulletin_board:company_view" company_id=job.company.id %}"
                       class="pxp-jobs-card-1-company">
                        {{ job.company.name }}
                    </a>
                </div>
                <a href="{% url "bulletin_board:company_view" company_id=job.company.id %}"
                   class="pxp-jobs-card-1-company-logo"
                        {% if job.company.brand_logo %}
                   style="background-image: url({{ job.company.brand_logo.url }});"
                        {% else %}
                   style="background-image: url({% system_image_company_default_logo_url %});"
                        {% endif %}
                ></a>
            </div>
        </div>
    </div>
{% endfor %}

backend/bulletin_board/templates/bulletin_board/components/social_links_v1.html
{% load cache %}
<div class="pxp-footer-social mt-3 mt-lg-0">
    {% cache 3600 social_links %}
        <ul class="list-unstyled" style="color: white">
            {% for social_link in social_links %}
                <li>
                    <a href="{{ social_link.url }}" style="color: white">
                        <span class="{{ social_link.icon_code }}"></span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endcache %}
</div>

backend/bulletin_board/templates/bulletin_board/components/summary.html
<div class="col-xxl-9 col-sm-6">
    <h4>{{content.app_inst.second_name}} {{ content.app_inst.first_name }} {{content.app_inst.middle_name}}</h4>
    <h4> {{ content.app_inst.name_app }} {% if content.app_inst.qualification != "Нет квалификации" %}  {{ content.app_inst.qualification }} {% endif %}</h4>
    <div class="col-xxl-10 col-sm-12">
        <h4>Ключевые навыки:</h4>
        <div class="pxp-single-candidate-skills">
            <ul class="list-unstyled">
                {% for tag in content.teg_inst %} <li>{{tag.title}}</li> {% endfor %}
            </ul>
        </div>
        <h4> Образование: </h4>
        {% for edu in content.education_inst %}
        <div class="col-xxl-12 col-sm-8 text-left border border-primary" style="border-radius: 15px; padding: 0.5%; margin-bottom: 0.5%;" >
            {{ edu.name }} | {{ edu.faculty }} | {{ edu.specialization }} | {{ edu.level }} |<br> с {{ edu.start_data|date:"d-m-Y" }} по {{edu.end_data|date:"d-m-Y"}}
        </div>
        {% endfor %}

        <h4> Опыт работы: </h4>
        {% for exp in content.experience_inst %}
        <div class="col-xxl-12 col-sm-8 text-left border border-primary" style="border-radius: 15px; padding: 0.5%; margin-bottom: 0.5%; word-wrap: break-word;">
            {{ exp.name }} | {{  exp.position }} | {{  exp.function }} |<br> с {{ exp.start_data|date:"d-m-Y" }} по {{exp.end_data|date:"d-m-Y"}}
        </div>
        {% endfor %}


        <h4>Дополнительная информация о себе:</h4>
        <p style="text-align: justify; word-wrap: break-word">{{ content.app_inst.about_app|safe }}</p>
    </div>
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-sm-12 col-xxl-4 text-left">
            <h4>Контактный телефон: </h4>
        </div>
        <div class="col-sm-12 col-xxl-4 text-left">
            <h4> {{ content.app_inst.tel }} </h4>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-sm-12 col-xxl-12 text-left"  style="font-size: 150%;">
            <a>Для просмотра контактной информации необходимо</a>
            <a href="{% url 'industrial:sign_in' %}">Войти</a>
            <a>или</a>
            <a href="{% url 'industrial:sign_up' %}">Зарегистрироваться</a>
        </div>
    </div>
    {% endif %}

</div>

<div class="col-xxl-3 col-sm-6" style="margin-bottom: 5%;">
    <div class="pxp-single-candidate-side-panel mt-5 mt-lg-0">Доп информация
        <div class="mt-4">
            <div class="pxp-single-candidate-side-info-label pxp-text-light">Опыт работы</div>
            <div class="pxp-single-candidate-side-info-data">{{ content.app_inst.experience }}</div>
        </div>
        <div class="mt-4">
            <div class="pxp-single-candidate-side-info-label pxp-text-light">Дата рождения</div>
            <div class="pxp-single-candidate-side-info-data">{{content.data}}</div>
        </div>
        {% if user.is_authenticated %}
        <div class="mt-4">
            <div class="pxp-single-candidate-side-info-label pxp-text-light">Телефон</div>
            <div class="pxp-single-candidate-side-info-data">{{ content.app_inst.tel }}</div>
        </div>
        {% endif %}

        {% if user.is_authenticated %}
        <div class="mt-4">
            <div class="pxp-single-candidate-side-info-label pxp-text-light">Электронная почта</div>
            <div class="pxp-single-candidate-side-info-data"><a>{{ content.app_inst.user.email }}</a></div>
        </div>
        {% endif %}
    </div>

    <div class="pxp-single-candidate-side-panel mt-4 mt-lg-5">Доп условия труда
        <div class="mt-4">
            <div class="pxp-single-candidate-side-info-label pxp-text-light">Ищу работу в</div>
            <div class="pxp-single-candidate-side-info-data">{{ content.app_inst.location }}</div>
        </div>
        <div class="mt-4">
            <div class="pxp-single-candidate-side-info-label pxp-text-light">Условия работы</div>
            <div class="pxp-single-candidate-side-info-data"><a>{{ content.app_inst.employment_type }}<br>{{ content.app_inst.work_schedule }}</a></div>
        </div>
        <div class="mt-4">
            <div class="pxp-single-candidate-side-info-label pxp-text-light">Ожидаемая заработная плата</div>
            <div class="pxp-single-candidate-side-info-data"><a>{{ content.app_inst.salary }} руб. {{ content.app_inst.salary_condition }}</a></div>
        </div>
    </div>
</div>




<!--<div class="row">-->
<!--    <div class="col col-xxl-4 col-sm-12 d-flex justify-content-center">-->
<!--        <div class="row" style="margin-bottom: 3%;">-->
<!--            <a href="{% url 'industrial:edit_summary' %}"><button class="btn btn-primary">Редактировать резюме</button></a>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="col col-xxl-4 col-sm-12 d-flex justify-content-center">-->
<!--        <form action="" method="post" >-->
<!--            {% csrf_token %}-->
<!--            {% if content.app_inst.show_on_main_page %}-->
<!--            <input  type="submit" value="Больше не ищу работу"  class="btn btn-danger" name="show">-->
<!--            {% else %}-->
<!--            <input type="submit" value="Разместить резюме на сайте" class="btn btn-primary" name="show">-->
<!--            {% endif %}-->
<!--        </form>-->
<!--    </div>-->


<!--</div>-->





<div class="modal fade pxp-user-modal" id="edu_modal" aria-hidden="true"
     aria-labelledby="need_to_pay_warning" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="pxp-user-modal-fig text-center">
                </div>
                <h4 class="modal-title text-center mt-4">
                    <a id="edu_name"></a><br>
                    <a id="edu_specialization"></a><br>
                    <a id="edu_level"></a><br>
                    <a>Начало обучения:&nbsp<br></a><a id="edu_start_data"></a><br>
                    <a>Конец обучения:&nbsp;<br></a><a id="edu_end_data"></a>
                </h4>

            </div>
        </div>
    </div>
</div>

<div class="modal fade pxp-user-modal" id="exp_modal" aria-hidden="true"
     aria-labelledby="need_to_pay_warning" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="pxp-user-modal-fig text-center">
                </div>
                <h4 class="modal-title text-center mt-4">
                    <a id="exp_name"></a><br>
                    <a id="exp_position"></a><br>
                    <a id="exp_function"></a><br>
                    <a>Начало работы:<br>&nbsp;</a><a id="exp_start_data"></a><br>
                    <a>Конец работы:<br>&nbsp;</a><a id="exp_end_data"></a>
                </h4>

            </div>
        </div>
    </div>
</div>

<script>
    function show_modal_edu(name, specialization, level, start_data, end_data){
        document.getElementById("edu_name").innerHTML = name;
        document.getElementById("edu_specialization").innerHTML = specialization;
        document.getElementById("edu_level").innerHTML = level;
        document.getElementById("edu_start_data").innerHTML = start_data;
        document.getElementById("edu_end_data").innerHTML = end_data;
        const myModal777 = new bootstrap.Modal(document.getElementById('edu_modal'))
        myModal777.show()
    }

    function show_modal_exp(name, position, functin, start_data, end_data) {
        document.getElementById("exp_name").innerHTML = name;
        document.getElementById("exp_position").innerHTML = position;
        document.getElementById("exp_function").innerHTML = functin;
        document.getElementById("exp_start_data").innerHTML = start_data;
        document.getElementById("exp_end_data").innerHTML = end_data;
        const myModal666 = new bootstrap.Modal(document.getElementById('exp_modal'))
        myModal666.show()
    }

</script>

backend/bulletin_board/templates/bulletin_board/components/template_part.html
{{ template_content|safe }}

backend/bulletin_board/templates/bulletin_board/components/total_companies_count_number.html
{% load industrial_tags %}
{% load cache %}

{% cache 20 total_jobs_count_component_cache %}
    {% total_companies_count %}
{% endcache %}

backend/bulletin_board/templates/bulletin_board/components/total_jobs_count_number.html
{% load industrial_tags %}
{% load cache %}

{% cache 20 total_jobs_count_component_cache %}
    {% total_published_jobs_count 1 %}
{% endcache %}