backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers


from django.contrib.sitemaps.views import sitemap
from bulletin_board.sitemaps import JobSitemap, CompanySitemap, ApplicantSitemap, BlogSitemap, CustomSitemap

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bulletin_board.urls')),

    path('industrial/', include('industrial.urls')),

    path('payment/', include('payment.urls')),

    path('api/v1/', include(router.urls)),
    path('api-auth/',
         include('rest_framework.urls', namespace='rest_framework')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('sitemap.xml', sitemap, {
        'sitemaps': {
            "jobs": JobSitemap,
            "companies": CompanySitemap,
            "applicants": ApplicantSitemap,
            "blog": BlogSitemap,
            "custom": CustomSitemap
        }
    },
         name='django.contrib.sitemaps.views.sitemap')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/drf/urls.py
# from django.contrib import admin
# from django.urls import path
# from . import views
# from django.views.decorators.csrf import csrf_exempt
#
# app_name = "drf"
#
# urlpatterns = [
#     path('dashboardapp_api/', csrf_exempt(views.DashboardAppAPI.as_view()),
#          name='dashboardapp_api'),
# ]

backend/industrial/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "industrial"

urlpatterns = [

    path('admin/request/publish_job_<int:job_id>',
         views.AdminPublishJob.as_view(), name='admin_publish_job'),
    path('admin/request/reject_job_<int:job_id>',
         views.AdminRejectJob.as_view(), name='admin_reject_job'),
    path('admin/request/close_job_<int:job_id>', views.AdminCloseJob.as_view(),
         name='admin_close_job'),

    path('reg-<str:user_ref_code>/', views.RefLinkView.as_view(),
         name='ref_link_view'),

    path('signin/', views.SignInView.as_view(), name='sign_in'),
    path('signinapp/', views.SignInAppView.as_view(), name='sign_in_app'),
    path('signupapp/', views.SignUpAppView.as_view(), name='sign_up_app'),
    path('get_company/', csrf_exempt(views.GetCompanyByInn.as_view()),
         name='get_company_by_inn'),

    path('signup/', views.SignUpView.as_view(), name='sign_up'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('confirm_email/', views.ConfirmEmailView.as_view(),
         name='confirm_email'),  # Поддтвержденые почты

    path('confirm_email_app/', views.ConfirmEmailAppView.as_view(),
         name='confirm_emailapp'),

    path('confirm_email/send_again',
         views.ResendConfirmEmailCodeView.as_view(),
         name='re_confirm_email_code'),  # Поддтвержденые почты

    path('confirm_email/send_againapp',
         views.ResendConfirmEmailCodeAppView.as_view(),
         name='re_confirm_email_codeapp'),  # Поддтвержденые почты

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

    path('dashboardapp/', views.DashboardAPP.as_view(), name='dashboardapp'),

    path('summary/', csrf_exempt(views.Summary.as_view()),
         name='summary'),

    path('edit_summary/', csrf_exempt(views.EditSummary.as_view()),
         name='edit_summary'),

    path('edit_summary/education/',
         csrf_exempt(views.EditSummaryEducation.as_view()),
         name='education'),

    path('edit_summary/experience/',
         csrf_exempt(views.EditSummaryExperience.as_view()),
         name='experience'),

    path('delete_tags/',
         csrf_exempt(views.TagsAPI.as_view()),
         name='delete_tags'),

    # path('delete_summary/education/',
    #      csrf_exempt(views.DeleteSummaryEducation.as_view()),
    #      name='delete_education'),
    #
    # path('delete_summary/experience/',
    #      csrf_exempt(views.DeleteSummaryExperience.as_view()),
    #      name='delete_experience'),

    path('profile/', views.Profile.as_view(), name='profile'),

    path('profile/edit_brand_info/', views.ProfileEditBrandInfo.as_view(),
         name='edit_brand_info'),

    path('profile/edit_administrator_info/',
         views.ProfileEditAdministratorInfo.as_view(),
         name='edit_administrator_info'),

    path('profile/edit_company_description/',
         views.ProfileEditCompanyDescription.as_view(),
         name='edit_company_description'),

    path('profile/edit_user_password/',
         views.ProfileEditUserPassword.as_view(), name='edit_user_password'),

    path('jobs/new', csrf_exempt(views.AddNewJob.as_view()), name='add_new_job'),
    path('jobs/list', csrf_exempt(views.JobsList.as_view()), name='jobs_list'),

    path('jobs/list_api', csrf_exempt(views.JobListAPI.as_view()),
         name='jobs_list_api'),
    path('jobs/pay_for_job_api', csrf_exempt(views.PayForJobAPI.as_view()),
         name='pay_for_job_api'),

    path('jobs/<int:job_id>/edit', csrf_exempt(views.EditJob.as_view()), name='edit_job'),
    path('jobs/<int:job_id>/view', views.ViewJob.as_view(), name='view_job'),
    path('jobs/<int:job_id>/delete', views.DeleteJob.as_view(),
         name='delete_job'),

    path('candidates/<int:resp_id>/delete', views.DeleteResponse.as_view(),
         name='delete_resp'),

    path('candidates/', views.CandidatesList.as_view(), name='candidates'),

    path('payment/', views.Payment.as_view(), name='payment'),

    path('user_agreement/', views.UserAgreement.as_view(),
         name='user_agreement'),
    path('instruction/', views.Instruction.as_view(), name='instruction'),
    path('support/', views.Support.as_view(), name='support'),

    path('user_agreementapp/', views.UserAgreementApp.as_view(),
         name='user_agreementapp'),
    path('instructionapp/', views.InstructionApp.as_view(), name='instructionapp'),
    path('supportapp/', views.SupportApp.as_view(), name='supportapp'),


    path('finance/', views.Finance.as_view(), name='finance'),

    path('payment_invoices/', views.PaymentInvoices.as_view(),
         name='payment_invoices'),

    path('payment_invoices/', views.PaymentInvoice.as_view(),
         name='payment_invoice'),
    path('payment_invoices/<int:invoice_id>/', views.PaymentInvoice.as_view(),
         name='payment_invoice'),
    path('payment_invoices/<int:invoice_id>/check',
         views.PaymentInvoiceCheck.as_view(), name='payment_invoice_check'),

    path('forgot_password/', views.ForgotPasswordView.as_view(),
         name='forgot_password'),
    path('enter_key/', views.EnterKeyView.as_view(),
         name='enter_key'),
    path('signre/', views.SignReView.as_view(), name='signre'),

]

backend/industrial/views.py
import json
import logging
import re
import secrets
from django.template.defaultfilters import lower
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, reverse, redirect
from django.template.defaultfilters import lower
from django.views import View
from django.http.response import HttpResponse, HttpResponseRedirect, \
    JsonResponse
from django.db.models import Count, Q

from backend.settings import env
from core_base import utils as core_utils
from core_base import services as cb_services
from core_base.logger import get_logger
from core_base.models import Tag, TagApp, EducationPlace, JobExperience
from . import forms
from . import utils
from . import services
from . import mixins
from django.utils import timezone

from django.contrib.auth import authenticate, login, logout

from core_base import models as cb_models
from industrial import models as in_models

from payment.selectors import get_company_payment_invoices, get_invoice_by_id
from payment import services as py_services

from django.conf import settings

from .models import Applicant, CompanyReferralChain, Company
# --- Функции для администратора ---------------
from .redis import r
from .services import password_reset, get_job_by_id, del_job_by_id, \
    del_response_by_id, find_user_in_base, add_or_update_app, \
    search_company_in_base, add_education, add_experience, delete_experience, \
    delete_education, do_tab, delete_ind_tags

logger = get_logger('myjobox_log', level=logging.INFO)


class AdminPublishJob(mixins.IsAdminMixin, View):
    def get(self, request, job_id: int):
        job_instance = services.get_job_by_id(job_id)

        if job_instance.status != 'published':
            # Если это ваканcия публикуется в первые
            if job_instance.published_at is None:
                job_instance.published_at = timezone.now()
                job_instance.expire_at = timezone.now() + timezone.timedelta(
                    days=30)

            job_instance.status = "published"
            job_instance.save()

        # Если прошло время
        if job_instance.expire_at < timezone.now():
            job_instance.status = "closed"

        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class AdminRejectJob(mixins.IsAdminMixin, View):
    def get(self, request, job_id: int):
        job_instance = services.get_job_by_id(job_id)

        job_instance.status = "rejected"
        job_instance.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class AdminCloseJob(mixins.IsAdminMixin, View):
    def get(self, request, job_id: int):
        job_instance = services.get_job_by_id(job_id)

        job_instance.status = "closed"
        job_instance.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


# --- Добавление Реферала в Cookies ------------
class RefLinkView(View):
    def get(self, request, user_ref_code):
        response = HttpResponseRedirect(reverse('industrial:sign_up'))
        response.set_cookie('ref_code', user_ref_code)
        print('user_ref_code', user_ref_code)
        return response


class SignInAppView(View):
    """Авторизация соискателя"""

    def get(self, request):
        return render(request, 'industrial/pages/signinapp.html', {})

    def post(self, request):
        sing_in_form = forms.SignInForm(request.POST)
        if sing_in_form.is_valid():
            username = lower(sing_in_form.cleaned_data['email'])
            password = sing_in_form.cleaned_data['password']
            try:
                user_ty = cb_models.User.objects.get(
                    email=lower(username)).user_type
            except:
                return render(request, 'industrial/pages/signinapp.html',
                              {'sing_in_error': True})

            user = authenticate(username=lower(username), password=password)
            if user is not None and user_ty == 'APPLICANT':
                login(request, user)
                return HttpResponseRedirect(reverse('industrial:dashboardapp'))
        return render(request, 'industrial/pages/signinapp.html',
                      {'sing_in_error': True})


class SignUpAppView(View):
    """Регистрация соискателя"""

    def get(self, request):
        return render(request, 'industrial/pages/signupapp.html', {})

    def post(self, request):
        errors = {
            "applicant_not_found": False,
            "different_passwords": False,
            "wrong_password": False,
            "tel_already_registered": False,
            "wrong_email": False,
            'applicant_already_registered': False,
        }
        rd = utils.dump_post_to_dict(request.POST)
        sign_upapp_form = forms.SignUpappForm(request.POST)
        req = request.POST
        print('rd', rd)

        if sign_upapp_form.is_valid():

            if find_user_in_base(lower(sign_upapp_form.cleaned_data['email'])):
                errors["applicant_already_registered"] = True

            if len(sign_upapp_form.cleaned_data['password']) < 8:
                errors["wrong_password"] = True

            if sign_upapp_form.cleaned_data['password'] != \
                    sign_upapp_form.cleaned_data['password_repeat']:
                errors["different_passwords"] = True

            if sign_upapp_form.cleaned_data['tel'] is None:
                errors["wrong_tel"] = True

            if not (errors["wrong_password"]
                    or errors["different_passwords"]
                    or errors["applicant_not_found"]
                    or errors["applicant_already_registered"]):

                registration_res = services.register_new_applicant(
                    email=lower(sign_upapp_form.cleaned_data['email']),
                    password=sign_upapp_form.cleaned_data['password'],
                    tel=sign_upapp_form.cleaned_data['tel']
                )
                print('registration_res', registration_res)

                if registration_res.email is not None:
                    return render(
                        request,
                        'industrial/pages/signinapp.html',
                        {'show_success_sign_up_message': True}
                    )
            else:
                return render(
                    request,
                    'industrial/pages/signupapp.html',
                    {
                        'errors': errors,
                        'rd': rd
                    }
                )
        return render(request, 'industrial/pages/signupapp.html',
                      {'sing_up_error': True})


class SignInView(View):
    """Авторизация компании"""

    def get(self, request):
        return render(request, 'industrial/pages/signin.html', {})

    def post(self, request):
        sing_in_form = forms.SignInForm(request.POST)
        if sing_in_form.is_valid():
            username = lower(sing_in_form.cleaned_data['email'])
            password = sing_in_form.cleaned_data['password']
            user = authenticate(username=lower(username), password=password)
            # user_ty = cb_models.User.objects.filter(email=username).first().user_type
            try:
                user_ty = cb_models.User.objects.get(
                    email=lower(username)).user_type
            except:
                return render(request, 'industrial/pages/signin.html',
                              {'sing_in_error': True})
            if user is not None and user_ty == 'INT':
                login(request, user)
                return HttpResponseRedirect(reverse('industrial:dashboard'))

        return render(request, 'industrial/pages/signin.html',
                      {'sing_in_error': True})


class SignUpView(View):
    """Регистрация компании"""

    def get(self, request):
        return render(request, 'industrial/pages/signup.html', {})

    def add_to_ref_chain(self, ref_code, referral_company):
        """ Добавить запись про рефералство"""

        affiliate_company = services.get_company_by_ref_code(ref_code)
        if affiliate_company:
            services.add_new_referral_chain(
                affiliate=affiliate_company,
                referral=referral_company,
                code=ref_code
            )

    def post(self, request):
        errors = {
            "company_not_found": False,
            "different_passwords": False,
            "wrong_password": False,
            "wrong_inn": False,
            'not_active': False,
            'company_already_registered': False,
            'email_already_registered': False,
        }
        rd = utils.dump_post_to_dict(request.POST)
        sign_up_form = forms.SignUpForm(request.POST)
        if sign_up_form.is_valid():

            clear_inn = sign_up_form.cleaned_data['inn']

            da_search = utils.DaDataCompany(search_query=int(clear_inn))
            da_search.do_search()
            company_info = da_search.searching_company_info

            if find_user_in_base(sign_up_form.cleaned_data['email']):
                errors["email_already_registered"] = True

            if search_company_in_base(sign_up_form.cleaned_data['inn']):
                errors['company_already_registered'] = True

            try:
                if clear_inn != company_info['inn']:
                    errors['company_not_found'] = True
            except:
                errors['company_not_found'] = True

            if len(sign_up_form.cleaned_data['password']) < 8:
                errors["wrong_password"] = True
            if sign_up_form.cleaned_data['password'] != \
                    sign_up_form.cleaned_data['password_repeat']:
                errors["different_passwords"] = True
            if company_info is None or sign_up_form.cleaned_data[
                'inn'] is None:
                errors["company_not_found"] = True
            if sign_up_form.cleaned_data['inn'] is None:

backend/industrial/templates/industrial/forms/admin_job_edit_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% block extrahead %}{{ block.super }}
    <script src="{% url 'admin:jsi18n' %}"></script>
    {{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
            &rsaquo; <a
                href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
            &rsaquo; {% if has_view_permission %}
            <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}
            {{ opts.verbose_name_plural|capfirst }}{% endif %}
            &rsaquo;
            {% if add %}{% blocktranslate with name=opts.verbose_name %}Add {{ name }}{% endblocktranslate %}{% else %}
                {{ original|truncatewords:"18" }}{% endif %}
        </div>
    {% endblock %}
{% endif %}

{% block content %}

    <div style="padding: 15px;">
        <a href="{% url 'industrial:admin_publish_job' job_id=object_id %}" class="btn btn-success">Публиковать</a>
        <a href="{% url 'industrial:admin_reject_job' job_id=object_id %}" class="btn btn-warning">Отклонить</a>
        <a href="{% url 'industrial:admin_close_job' job_id=object_id %}" class="btn btn-danger">Закрыть</a>
    </div>

    <div>
        <br>
        {{ opts }}
        <hr>
        <br>
    </div>

    <style>
        .btn {
            padding: 10px;
            margin-right: 20px;
        }

        .btn-success {
            background: limegreen;
            border-radius: 5px;
            color: white !important;
        }

        .btn-warning {
            background: yellow;
            border-radius: 5px;
            color: black !important;
        }

        .btn-danger {
            background: red;
            border-radius: 5px;
            color: white !important;
        }
    </style>

    <div id="content-main">
        {% block object-tools %}
            {% if change %}{% if not is_popup %}
                <ul class="object-tools">
                    {% block object-tools-items %}
                        {% change_form_object_tools %}
                    {% endblock %}
                </ul>
            {% endif %}{% endif %}
        {% endblock %}
        <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}{% if form_url %}action="{{ form_url }}" {% endif %}method="post"
              id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
            <div>
                {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1">{% endif %}
                {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}">{% endif %}
                {% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
                {% if errors %}
                    <p class="errornote">
                        {% if errors|length == 1 %}{% translate "Please correct the error below." %}{% else %}
                            {% translate "Please correct the errors below." %}{% endif %}
                    </p>
                    {{ adminform.form.non_field_errors }}
                {% endif %}

                {% block field_sets %}
                    {% for fieldset in adminform %}
                        {% include "admin/includes/fieldset.html" %}
                    {% endfor %}
                {% endblock %}

                {% block after_field_sets %}{% endblock %}

                {% block inline_field_sets %}
                    {% for inline_admin_formset in inline_admin_formsets %}
                        {% include inline_admin_formset.opts.template %}
                    {% endfor %}
                {% endblock %}

                {% block after_related_objects %}{% endblock %}

                {% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

                {% block admin_change_form_document_ready %}
                    <script id="django-admin-form-add-constants"
                            src="{% static 'admin/js/change_form.js' %}"
                            {% if adminform and add %}
                            data-model-name="{{ opts.model_name }}"
                            {% endif %}
                            async>
                    </script>
                {% endblock %}

                {# JavaScript for prepopulated fields #}
                {% prepopulated_fields_js %}

            </div>
        </form>
    </div>
{% endblock %}